### PR TITLE
Test on some major JDK versions

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by Goooler** [comment]
See https://scans.gradle.com/s/22yhs6y2gul2a/tests/overview

**Comment by Goooler** [comment]
https://scans.gradle.com/s/gdekmmkvnwdfu/tests/task/:test/details/me.champeau.gradle.ReportsFunctionalTest/can%20generate%20an%20HTML%20report?top-execution=1

**Comment by melix** [comment]
Thanks @Goooler would you mind rebasing your PR?

**Comment by Goooler** [comment]
It's https://github.com/melix/japicmp-gradle-plugin/pull/63.

**Pull request closed without merging**
